import java.util.*;import java.io.*;
public class PMS{
static class g{int i;String n;String e;String p;boolean v;g(int i,String n,String e,String p,boolean v){this.i=i;this.n=n;this.e=e;this.p=p;this.v=v;}}
static class P{int i;String n;String d;String v;String x;List<Integer>igs=new ArrayList<>();List<E>es=new ArrayList<>();P(int i,String n,String d,String v,String x){this.i=i;this.n=n;this.d=d;this.v=v;this.x=x;}}
static class R{int g,p;boolean a;R(int g,int p,boolean a){this.g=g;this.p=p;this.a=a;}}
static class E{String i;double a;E(String i,double a){this.i=i;this.a=a;}}
static Map<Integer,g>G=new HashMap<>();static Map<Integer,P>P=new HashMap<>();static List<R>R=new ArrayList<>();static int gi=1,pi=1;
public static void main(String[]A){Scanner S=new Scanner(System.in);System.out.println("PMS START");while(true){System.out.println("1G 2P 3R 4E 5T 0X");String c=S.nextLine();if(c.equals("1"))G(S);else if(c.equals("2"))P(S);else if(c.equals("3"))R(S);else if(c.equals("4"))E(S);else if(c.equals("5"))T(S);else if(c.equals("0"))break;else System.out.println("???");}}static void G(Scanner s){for(;;){System.out.println("1add 2v 3u 4d 0b");String c=s.nextLine();if(c.equals("1"))aG(s);else if(c.equals("2"))vG();else if(c.equals("3"))uG(s);else if(c.equals("4"))dG(s);else if(c.equals("0"))return;else System.out.println("err");}}static void aG(Scanner s){System.out.print("nm:");String n=s.nextLine();System.out.print("em:");String e=s.nextLine();System.out.print("ph:");String p=s.nextLine();System.out.print("vip?y/n");boolean v=s.nextLine().equalsIgnoreCase("y");g gg=new g(gi++,n,e,p,v);G.put(gg.i,gg);System.out.println("ADDED:"+gg.i);}
static void vG(){if(G.isEmpty()){System.out.println("NONE");return;}for(g x:G.values()){System.out.println(x.i+" "+x.n+" "+x.e+" "+x.p+" VIP:"+x.v);}}
static void uG(Scanner s){System.out.print("id:");try{int i=Integer.parseInt(s.nextLine());g g=G.get(i);if(g==null){System.out.println("NF");return;}System.out.print("nm("+g.n+")");String n=s.nextLine();if(!n.isEmpty())g.n=n;System.out.print("em("+g.e+")");String e=s.nextLine();if(!e.isEmpty())g.e=e;System.out.print("ph("+g.p+")");String p=s.nextLine();if(!p.isEmpty())g.p=p;System.out.print("vip?y/n");String v=s.nextLine();if(!v.isEmpty())g.v=v.equalsIgnoreCase("y");System.out.println("upd");}catch(Exception q){System.out.println("bad id");}}
static void dG(Scanner s){System.out.print("id:");try{int i=Integer.parseInt(s.nextLine());if(G.remove(i)!=null)System.out.println("del");else System.out.println("nf");}catch(Exception e){System.out.println("no");}}static void P(Scanner s){for(;;){System.out.println("1c 2v 3u 4d 5i 6r 7l 0b");String c=s.nextLine();if(c.equals("1"))cP(s);else if(c.equals("2"))vP();else if(c.equals("3"))uP(s);else if(c.equals("4"))dP(s);else if(c.equals("5"))iP(s);else if(c.equals("6"))rP(s);else if(c.equals("7"))lP(s);else if(c.equals("0"))return;else System.out.println("err");}}static void cP(Scanner s){System.out.print("nm:");String n=s.nextLine();System.out.print("dt:");String d=s.nextLine();System.out.print("vn:");String v=s.nextLine();System.out.print("ds:");String x=s.nextLine();P p=new P(pi++,n,d,v,x);P.put(p.i,p);System.out.println("crtd"+p.i);}static void vP(){if(P.isEmpty()){System.out.println("none");return;}for(P p:P.values())System.out.println(p.i+" "+p.n+" "+p.d+" "+p.v);}static void uP(Scanner s){try{int i=Integer.parseInt(s.nextLine());P p=P.get(i);if(p==null){System.out.println("nf");return;}System.out.print("nm("+p.n+")");String n=s.nextLine();if(!n.isEmpty())p.n=n;}catch(Exception e){System.out.println("bad");}}static void dP(Scanner s){try{int i=Integer.parseInt(s.nextLine());P.remove(i);System.out.println("rmv");}catch(Exception e){System.out.println("bad");}}
static void iP(Scanner s){try{System.out.print("pid:");int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);if(p==null){System.out.println("no");return;}System.out.print("gid:");int gid=Integer.parseInt(s.nextLine());if(!G.containsKey(gid)){System.out.println("no g");return;}if(p.igs.contains(gid))System.out.println("alr");else{p.igs.add(gid);System.out.println("ok");}}catch(Exception e){System.out.println("bad");}}
static void rP(Scanner s){try{int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);System.out.print("gid:");int gid=Integer.parseInt(s.nextLine());p.igs.remove((Integer)gid);}catch(Exception e){System.out.println("bad");}}
static void lP(Scanner s){try{int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);for(int gid:p.igs){g g=G.get(gid);System.out.println(g.i+" "+g.n);}if(p.igs.isEmpty())System.out.println("none");}catch(Exception e){System.out.println("err");}}static void R(Scanner s){for(;;){System.out.println("1a 2p 3g 4r 0b");String c=s.nextLine();if(c.equals("1"))aR(s);else if(c.equals("2"))pR(s);else if(c.equals("3"))gR(s);else if(c.equals("4"))rR(s);else if(c.equals("0"))return;else System.out.println("err");}}static void aR(Scanner s){try{System.out.print("pid:");int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);System.out.print("gid:");int gid=Integer.parseInt(s.nextLine());System.out.print("att?y/n");boolean att=s.nextLine().equalsIgnoreCase("y");boolean f=false;for(R r:R){if(r.g==gid&&r.p==pid){r.a=att;f=true;}}if(!f)R.add(new R(gid,pid,att));System.out.println("ok");}catch(Exception e){System.out.println("bad");}}
static void pR(Scanner s){try{int pid=Integer.parseInt(s.nextLine());for(R r:R){if(r.p==pid){g g=G.get(r.g);System.out.println(g.n+" "+r.a);}}}catch(Exception e){System.out.println("bad");}}
static void gR(Scanner s){try{int gid=Integer.parseInt(s.nextLine());for(R r:R){if(r.g==gid){P p=P.get(r.p);System.out.println(p.n+" "+r.a);}}}catch(Exception e){System.out.println("bad");}}
static void rR(Scanner s){try{int pid=Integer.parseInt(s.nextLine());int gid=Integer.parseInt(s.nextLine());Iterator<R>it=R.iterator();while(it.hasNext()){R r=it.next();if(r.g==gid&&r.p==pid)it.remove();}}catch(Exception e){System.out.println("bad");}}static void E(Scanner s){for(;;){System.out.println("1a 2v 3r 0b");String c=s.nextLine();if(c.equals("1"))aE(s);else if(c.equals("2"))vE(s);else if(c.equals("3"))rE(s);else if(c.equals("0"))return;else System.out.println("err");}}static void aE(Scanner s){try{int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);System.out.print("itm:");String i=s.nextLine();System.out.print("amt:");double a=Double.parseDouble(s.nextLine());p.es.add(new E(i,a));}catch(Exception e){System.out.println("bad");}}
static void vE(Scanner s){try{int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);double t=0;for(E e:p.es){System.out.println(e.i+":"+e.a);t+=e.a;}System.out.println("t="+t);}catch(Exception e){System.out.println("bad");}}
static void rE(Scanner s){try{int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);String i=s.nextLine();Iterator<E>it=p.es.iterator();while(it.hasNext()){E e=it.next();if(e.i.equals(i))it.remove();}}catch(Exception e){System.out.println("bad");}}
static void T(Scanner s){for(;;){System.out.println("1A 2V 3E 4G 0b");String c=s.nextLine();if(c.equals("1"))tA(s);else if(c.equals("2"))tV(s);else if(c.equals("3"))tE(s);else if(c.equals("4"))tG();else if(c.equals("0"))return;else System.out.println("bad");}}static void tA(Scanner s){try{int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);int y=0,n=0;Set<Integer>d=new HashSet<>();for(R r:R){if(r.p==pid){if(r.a)y++;else n++;d.add(r.g);}}int pend=p.igs.size()-d.size();System.out.println("YES:"+y+" NO:"+n+" PEND:"+pend);}catch(Exception e){System.out.println("bad");}}static void tV(Scanner s){try{int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);for(int gid:p.igs){g g=G.get(gid);if(g.v)System.out.println(g.n);}}catch(Exception e){System.out.println("bad");}}static void tE(Scanner s){try{int pid=Integer.parseInt(s.nextLine());P p=P.get(pid);double t=0;for(E e:p.es)t+=e.a;System.out.println("Total:"+t);}catch(Exception e){System.out.println("bad");}}static void tG(){for(g g:G.values()){int inv=0,att=0;for(P p:P.values()){if(p.igs.contains(g.i))inv++;for(R r:R){if(r.g==g.i&&r.p==p.i&&r.a)att++;}}System.out.println(g.n+" inv:"+inv+" att:"+att);}}
}
